services:
  mysql:
    image: mysql/mysql:latest
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: tour
      MYSQL_PASSWORD:
      MYSQL_USERNAME: root
    container_name: mysql
    networks:
      - mysql-net
  aplicacao:
    image: macedoldm/tour
    ports:
      - 8080:8080
    environment:
      MYSQL_HOST: jdbc:mysql://mysql:3306/tour
    depends_on:
      - mysql
    container_name: psw
    networks:
      - mysql-net
networks:
  mysql-net:
    driver: bridge