spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tour
    username: root
    password:
  jpa:
      show-sql: true
      hibernate:
        ddl-auto: none
      generate-ddl: true
